---
- name: dotnet for windows
  include_tasks: windows.yml
  register: dotnet_result_win
  when:
  - inventory_hostname == 'localwinrm'
  - "'win' in targets"

- name: dotnet for wsl
  include_tasks: el9.yml
  register: dotnet_result_wsl
  when:
  - inventory_hostname == 'localhost'
  - ansible_os_family == 'RedHat'
  - ansible_distribution_major_version == '9'
  - "'wsl' in targets"
