---
- name: Install dotnet for windows
  win_chocolatey:
    allow_pre_release: "{{ roles.dotnet.allow_pre_release | default(omit) }}"
    name: dotnetcore-sdk
    state: "{{ roles.dotnet.state | default(omit) }}"
    version: "{{ roles.dotnet.version | default(omit) }}"
