---
- name: Install dotnet for windows
  win_chocolatey:
    allow_prerelease: "{{ roles.dotnet.allow_prerelease | default(omit) }}"
    name: dotnetcore-sdk
    state: "{{ roles.dotnet.state | default(omit) }}"
    version: "{{ roles.dotnet.version | default(omit) }}"
