---
- name: Install vim package
  apt:
    cache_valid_time: 600
    name: "{{ packages }}"
  vars:
    packages:
    - vim
  become: yes

- name: Ensure vim autoload folder exists
  file:
    path: "{{ ansible_env['HOME'] }}/.vim/autoload"
    state: directory

- name: Install vimplug
  get_url:
    dest: "{{ ansible_env['HOME'] }}/.vim/autoload/plug.vim"
    url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

- name: Non-local vimrc
  block:

  - name: Fetch custom vimrc
    get_url:
      dest: "{{ ansible_env['HOME'] }}/.vimrc"
      force: yes
      url: "{{ roles.wsl_vim.vimrc_url }}"
    when:
    - roles.wsl_vim.vimrc_url is defined
    notify: "install vim plugins"

  - name: Copy vimrc
    copy:
      src: .vimrc
      dest: "{{ ansible_env['HOME'] }}/.vimrc"
    when:
    - roles.wsl_vim.vimrc_url is not defined
    notify: "install vim plugins"

  when:
  - (roles.wsl_vim.vimrc_local is not defined) or (not roles.wsl_vim.vimrc_local)

