---
- name: Check current go version
  command: "{{ wsl_install_dir }}/bin/go version"
  changed_when: false
  failed_when: false
  register: roles_golang_current_version

- block:

  - name: Remove old version of wsl golang
    file:
      path: "{{ wsl_install_dir }}"
      state: absent
    become: yes

  - name: Ensure {{ wsl_install_dir }}
    file:
      path: "{{ wsl_install_dir }}"
      state: directory
      mode: 0755
    become: yes
  
  - name: Download wsl golang
    get_url:
      dest: "{{ wsl_install_dir }}/{{ wsl_archive_name }}"
      url: "{{ download_url_base }}/{{ wsl_archive_name }}"
    become: yes
  
  - name: Unarchive wsl golang
    unarchive:
      dest: /usr/local/go
      extra_opts:
      - --strip-components
      - "1"
      remote_src: yes
      src: "{{ wsl_install_dir }}/{{ wsl_archive_name }}"
    become: yes

  when:
  - roles_golang_current_version.stdout != "go version go" + version + " linux/amd64"
  
- name: Add go bin to path
  copy:
    content: "export PATH=$PATH:/usr/local/go/bin"
    dest: /etc/profile.d/dev_bootstrap_go.sh
    mode: 0644
  become: yes
#- name: Set wsl_golang_archive
#  set_fact:
#    wsl_golang_archive: "go{{ roles.wsl_golang.version | default(wsl_golang_default_version) }}{{ wsl_golang_download_url_extension }}"
#
#- name: Set wsl_golang_download_url
#  set_fact:
#    wsl_golang_download_url: "{{ wsl_golang_download_url_base }}{{ wsl_golang_archive }}"
#
#- name: Ensure /opt/ansible/wsl_golang
#  file:
#    path: /opt/ansible/wsl_golang
#    state: directory
#    mode: 0700
#  become: yes
#
#- name: Download wsl_golang
#  get_url:
#    dest: "/opt/ansible/wsl_golang/{{ wsl_golang_archive }}"
#    url: "{{ wsl_golang_download_url }}"
#  become: yes
#  register: wsl_golang_download_result
#
#- name: install wsl_golang
#  block:
#
#  - name: Remove old version of wsl_golang
#    file:
#      path: /usr/local/go
#      state: absent
#
#  - name: Unarchive wsl_golang
#    unarchive:
#      dest: /usr/local
#      remote_src: yes
#      src: "/opt/ansible/wsl_golang/{{ wsl_golang_archive }}"
#
#  - name: Add go bin to path
#    copy:
#      content: "export PATH=$PATH:/usr/local/go/bin"
#      dest: /etc/profile.d/go.sh
#      mode: 0644
#
#  become: yes
#  when: wsl_golang_download_result.changed
