---
- name: golang for windows
  include_tasks: windows.yml
  register: golang_result_win
  when:
  - inventory_hostname == 'localwinrm'
  - "'win' in roles.golang.targets"

- name: golang for wsl
  include_tasks: el9.yml
  register: golang_result_wsl
  when:
  - inventory_hostname == 'localhost'
  - ansible_os_family == 'RedHat'
  - ansible_distribution_major_version == '9'
  - "'wsl' in roles.golang.targets"
