---
- name: golang for windows
  include_tasks: windows.yml
  vars:
    ansible_user: "{{ win_ansible_vars.ansible_user }}"
    ansible_password: "{{ win_ansible_vars.ansible_password }}"
    ansible_connection: "{{ win_ansible_vars.ansible_connection }}"
    ansible_winrm_transport: "{{ win_ansible_vars.ansible_winrm_transport }}"
    ansible_winrm_server_cert_validation: "{{ win_ansible_vars.ansible_winrm_server_cert_validation }}"
  register: golang_result

