---
- name: Install golang
  win_chocolatey:
    force: yes
    name: golang
    state: "{{ roles.golang.state | default(omit) }}"
    version: "{{ roles.golang.version | default(golang_default_version) }}"

