---
- hosts: localhost
  connection: local

  vars:
    win_ansible_vars:
      ansible_user: "{{ wincreds.username }}"
      ansible_password: "{{ wincreds.password }}"
      ansible_connection: winrm
      ansible_winrm_transport: "{{ win_ansible_winrm_transport | default('basic') }}"
      ansible_winrm_server_cert_validation: ignore

  tasks:

  - name: set configured roles empty
    set_fact:
      configured_roles: "{{ roles | default({}) }}"

  - name: fetch external configured roles
    include_role:
      name: fetch_external
    loop: "{{ external.repos }}"
    loop_control:
      loop_var: repo
    when:
    - external is defined
    - external.repos is defined

  - name: configured roles
    debug:
      var: configured_roles

  - name: include all configured roles
    include_tasks: include_tasks/update_configured_role.yml
    loop: "{{ configured_roles | by_role_weight }}"
    loop_control:
      loop_var: configured_role
