---
- hosts: localhost
  connection: local

  vars:
    win_ansible_vars:
      ansible_user: "{{ wincreds.username }}"
      ansible_password: "{{ wincreds.password }}"
      ansible_connection: winrm
      ansible_winrm_transport: "{{ win_ansible_winrm_transport | default('basic') }}"
      ansible_winrm_server_cert_validation: ignore

  tasks:

  - name: Include all roles from inventory variables
    include_role:
      name: "{{ item.key }}"
    loop: "{{ roles | dict2items }}"
    when: roles

