---
- block:

  - name: set dynamic external symlink for {{ configured_role.name }}
    file:
      src: "{{ configured_role.config.dev_bootstrap_dynamic_external }}"
      dest: .dynamic-external
      state: link
    changed_when: False
    tags:
    - always
    when: configured_role.config.dev_bootstrap_dynamic_external is defined
  
  - name: include configured role {{ configured_role.name }}
    include_role:
      name: "{{ configured_role.name }}"
    tags:
    - always

  always:

  - name: remove dynamic external symlink for {{ configured_role.name }}
    file:
      dest: .dynamic-external
      state: absent
    changed_when: False
    tags:
    - always
    when: configured_role.config.dev_bootstrap_dynamic_external is defined

