---
# Outlined in the docker install guide:
#   https://docs.docker.com/install/linux/docker-ce/ubuntu/#install-using-the-repository

- name: Install packages to allow apt to use a repository over HTTPS
  apt:
    cache_valid_time: 600
    name: "{{ packages }}"
  vars:
    packages:
    - apt-transport-https
    - ca-certificates
    - curl
    - software-properties-common
  become: yes

- name: Add Docker’s official GPG key
  apt_key:
    id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
  become: yes

- name: Add Docker's official apt repository
  apt_repository:
    repo: >
      deb [arch=amd64] https://download.docker.com/linux/ubuntu
      {{ ansible_distribution_release }}
      stable
    state: present
  become: yes
  register: roles_wsl_docker_add_apt_repo

- name: Update apt cache after adding docker apt repository
  apt:
    update_cache: yes
  become: yes
  when: roles_wsl_docker_add_apt_repo.changed

- name: Install the latest version of Docker CE
  apt:
    cache_valid_time: 600
    name: docker-ce
  become: yes

- name: Configure docker client
  copy:
    dest: /etc/profile.d/docker.sh
    content: export DOCKER_HOST=tcp://127.0.0.1:2375
  become: yes

- name: Obtain docker-compose
  get_url:
    dest: /usr/local/bin/docker-compose
    mode: 0755
    url: "https://github.com/docker/compose/releases/download/{{ roles.wsl_docker.docker_compose.version | default('1.23.1', true) }}/docker-compose-{{ ansible_system }}-{{ ansible_architecture }}"
    checksum: "sha256:https://github.com/docker/compose/releases/download/{{ roles.wsl_docker.docker_compose.version | default('1.23.1', true) }}/docker-compose-{{ ansible_system }}-{{ ansible_architecture }}.sha256"
  when: roles.wsl_docker.docker_compose is defined
  become: yes
