---
- name: vscode for windows
  include_tasks: windows.yml
  vars:
    ansible_user: ansible
    ansible_password: set4now
    ansible_connection: winrm
    ansible_winrm_transport: basic
    ansible_winrm_server_cert_validation: ignore
  register: vscode_result

