---
- name: Install vscode
  win_chocolatey:
    name: vscode
    state: "{{ roles.vscode.state | default(omit) }}"
    version: "{{ roles.vscode.version | default(omit) }}"
  register: vscode_result
  when:
  - inventory_hostname == 'localwinrm'
