---
- name: Setup the stable docker repo
  ansible.builtin.get_url:
    dest: /etc/yum.repos.d/docker-ce.repo
    url: https://download.docker.com/linux/centos/docker-ce.repo
  become: yes

- name: Docker packages
  ansible.builtin.dnf:
    name: "{{ dnf_package_list }}"
    state: present
  become: yes

- name: Podman packages
  ansible.builtin.dnf:
    name:
    - podman
    # nobest required for docker and podman to co-exist
    nobest: true
    state: present
  become: yes

# need to upgrade because older versions fail to reinstall if they're no longer available
# reinstall fails if a new shadow-utils has been released, the old patch-level is no longer
# present in the repository.
- name: Upgrade shadow-utils to ensure reinstall will succeed
  ansible.builtin.shell: dnf upgrade --assumeyes shadow-utils
  become: yes
  changed_when: false

# need re-install shadow-utils or you get newuidmap permission denied
#   https://github.com/containers/podman/issues/7749#issuecomment-697557045
- name: Fix setuid capabilities on newuidmap/newgidmap
  ansible.builtin.shell: dnf reinstall --assumeyes shadow-utils
  become: yes
  changed_when: false

- name: Enable IP forwarding
  ansible.posix.sysctl:
    name: net.ipv4.ip_forward
    value: '1'
    sysctl_set: yes
  become: yes

- name: Add user to docker group
  ansible.builtin.user:
    name: '{{ ansible_user_id }}'
    groups: docker
    append: yes
  become: yes

- name: Enable docker systemd service
  ansible.builtin.systemd:
    daemon_reload: yes
    name: docker
    enabled: yes
    state: started
  become: yes

# We need to create the .kube folder so kubeadm doesn't create
# it as root when first starting minikube
- name: Make minikube and .kube folders folder
  ansible.builtin.file:
    path: "/home/{{ ansible_user_id }}/.kube/"
    mode: '0700'
    state: directory

- name: Download minikube
  ansible.builtin.get_url:
    dest: /usr/local/bin/minikube
    mode: 0755
    url: "https://github.com/kubernetes/minikube/releases/download/v{{ minikube_version }}/minikube-linux-amd64"
    checksum: "{{ minikube_checksum }}"
  become: yes

- name: Install kubectl
  get_url:
    checksum: "{{ kubectl_checksum }}"
    dest: /usr/local/bin/kubectl
    mode: 0755
    url: "{{ kubectl_url }}"
  become: yes

- name: Add containerd ulimit systemd unit override folder
  ansible.builtin.file:
    path: /etc/systemd/system/containerd.service.d
    owner: root
    mode: '0755'
    group: root
    state: directory
  become: yes

- name: Files
  ansible.builtin.copy:
    force: yes
    src: "{{ file }}"
    dest: /{{ file }}
  become: yes
  loop: "{{ files }}"
  loop_control:
    loop_var:  file

- name: Templates
  ansible.builtin.template:
    force: yes
    src: "{{ template }}"
    dest: /{{ file }}
  become: yes
  loop: "{{ templates }}"
  loop_control:
    loop_var:  template
  vars:
    file: "{{ template | replace('.j2', '') }}"

- name: Enable minikube systemd service
  ansible.builtin.systemd:
    daemon_reload: yes
    name: minikube
    enabled: yes
    state: started
  become: yes
