---
- name: container host for el 9
  include_tasks: el9.yml
  when:
  - inventory_hostname == 'localhost'
  - ansible_os_family == 'RedHat'
  - ansible_distribution_major_version == '9'
  register: container_host_result
