---
# As outlined by: https://docs.microsoft.com/en-us/windows-server/administration/openssh/openssh_install_firstuse
- name: Check windows capability
  win_shell: |
    (Get-WindowsCapability -Online -Name 'OpenSSH.Server~~~~0.0.1.0').State
  changed_when: false
  register: roles_openssh_server_capability_state

- name: Install OpenSSH.Server
  block:

  - name: Add openssh server capability
    win_shell: |
      Add-WindowsCapability -Online -Name 'OpenSSH.Server~~~~0.0.1.0'

  - name: Set default shell
    win_regedit:
      path: HKLM:\SOFTWARE\OpenSSH
      name: DefaultShell
      data: "{{ configured_role.config.default_shell | default('C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\powershell.exe') }}"
      type: string

  - name: Start sshd service
    win_service:
      name: sshd
      start_mode: auto
      state: started

  when: roles_openssh_server_capability_state.stdout_lines[0] != 'Installed'
