---
# Outlined in the dotnet core sdk install guide:
#   https://www.microsoft.com/net/download/linux-package-manager/ubuntu18-04/sdk-current

- name: "Install packages-microsoft-prod.deb"
  apt: 
    deb: https://packages.microsoft.com/config/ubuntu/{{ ansible_distribution_version }}/packages-microsoft-prod.deb
  become: yes
  register: roles_wsl_dotnet_add_apt_repo

- name: Update apt cache after adding dotnet apt repository
  apt:
    update_cache: yes
  become: yes
  when: roles_wsl_dotnet_add_apt_repo.changed

- name: "Install dotnet >= 3.0 < 5.0 package"
  apt:
    cache_valid_time: 600
    name: "{{ packages }}"
  vars:
    packages:
    - apt-transport-https
    - dotnet-sdk-{{ roles.dotnet.version }}
  become: yes
  when:
  - roles.dotnet.version is defined
  - roles.dotnet.version is version('3.0', operator='ge', strict=True)
  - roles.dotnet.version is version('5.0', operator='lt', strict=True)

- name: "Install dotnet >= 5.0 package"
  apt:
    cache_valid_time: 600
    name: "{{ packages }}"
  vars:
    packages:
    - apt-transport-https
    - dotnet-sdk-{{ roles.dotnet.version | default('5.0') }}
  become: yes
  when: (roles.dotnet.version is not defined) or
    (
      (roles.dotnet.version is version('3.0', operator='ge', strict=True))
      and (roles.dotnet.version is version('5.0', operator='lt', strict=True))
    )
