---
- name: Set wsl_golang_state
  set_fact:
    wsl_golang_state: "{{ roles.wsl_golang.state if roles is defined and roles.wsl_golang is defined and roles.wsl_golang.state is defined else 'present' }}"

- name: Uninstall wsl_golang
  include_tasks: uninstall.yml
  when: (wsl_golang_state == "absent") or (wsl_golang_state == "reinstall")
  register: wsl_golang_uninstall_result

- name: Install wsl_golang
  include_tasks: install.yml
  when: (wsl_golang_state == "present") or (wsl_golang_state == "reinstall")
  register: wsl_golang_install_result

- name: wsl_golang_state not supported
  fail:
    msg: "Unsupported state: {{ wsl_golang_state }}"
  when:
  - wsl_golang_install_result is skipped
  - wsl_golang_uninstall_result is skipped
